In [3]:
import numpy as np

np.random.seed(123)

def initialize_grid(shape, states):
    """Inicializa una grilla con valores aleatorios entre 0 y m."""
    return np.random.randint(0, states + 1, size=shape)

def get_neighbors_sum(grid, r):
    """Calcula la suma de los valores en la vecindad de radio r utilizando broadcasting."""
    from scipy.ndimage import uniform_filter
    
    neighborhood_size = (2 * r + 1,) * grid.ndim
    summed_neighbors = uniform_filter(grid.astype(float), size=neighborhood_size, mode='wrap') * (grid.size / np.prod(neighborhood_size))
    return summed_neighbors - grid  # Restamos la celda misma

def update_grid(grid, states, r):
    """Actualiza la grilla según las reglas dadas."""
    sum_neighbors = get_neighbors_sum(grid, r)
    max_sum = states * (np.prod([2 * r + 1] * grid.ndim) - 1)
    intervals = np.linspace(0, max_sum, 4)
    
    new_grid = grid.copy()
    new_grid[(sum_neighbors >= intervals[0]) & (sum_neighbors < intervals[1])] -= 1
    new_grid[(sum_neighbors >= intervals[1]) & (sum_neighbors < intervals[2])] += 1
    new_grid[(sum_neighbors >= intervals[2])] -= 1
    
    new_grid = np.clip(new_grid, 0, states)  # Aseguramos que los valores estén entre 0 y m
    return new_grid

def run_simulation(shape, states, r, steps):
    """Ejecuta la simulación del autómata por un número dado de pasos."""
    grid = initialize_grid(shape, states)
    for _ in range(steps):
        grid = update_grid(grid, states, r)
        print(grid) 
    return grid

# Ejemplo de uso
grid_final = run_simulation((10, 10), 1, 1, 10)
print("grid final:")
print(grid_final)


[[0 0 0 1 1 1 0 1 1 1]
 [1 1 0 1 1 1 1 1 1 1]
 [1 0 0 0 1 1 1 1 1 1]
 [1 1 0 0 0 0 1 0 0 0]
 [0 1 0 1 1 1 1 0 0 1]
 [1 1 0 1 1 1 0 0 0 1]
 [0 1 0 1 1 1 0 0 1 1]
 [1 1 1 1 1 0 0 1 1 1]
 [1 0 0 0 0 1 1 1 1 1]
 [1 1 1 0 1 1 1 0 1 1]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 1 0]
 [0 1 0 1 0 0 1 0 0 1]
 [0 1 0 0 0 0 1 0 1 1]
 [0 0 0 0 0 1 1 1 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]]
[[0 1 0 1 0 0 0 0 0 0]
 [0 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [1 1 0 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 1 1 1]
 [1 0 1 0 0 1 1 0 1 1]
 [1 1 1 0 0 1 1 1 1 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]]
[[0 1 0 1 1 0 0 0 0 0]
 [0 1 1 1 1 0 0 0 0 0]
 [1 1 1 0 1 1 0 0 0 0]
 [1 1 1 1 1 0 0 0 1 1]
 [0 1 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 0 0 0 0]
 [1 0 1 1 0 1 0 0 1 0]
 [1 0 1 1 0 1 1 1 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]]
[[1 1 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1]
 [0 0 0